csceFaculty = [
    "Riccardo Bettati",
    "Marcus Botacin",
    "Martin Carlisle",
    "James Caverlee",
    "Christiana Chamon",
    "Theodora Chaspari",
    "Jianer Chen",
    "Yoonsuck Choe",
    "Victoria Crawford",
    "Dilma Da Silva",
    "Tim Davis",
    "Paula deWitte",
    "Juan Garay",
    "Guofei Gu",
    "Ricardo Gutierrez-Osuna",
    "Drew Hamilton",
    "Tracy Anne Hammond",
    "Maristela Holanda",
    "Jeff Huang",
    "Ruihong Huang",
    "Thomas R. Ioerger",
    "Shuiwang Ji",
    "Anxiao (Andrew) Jiang",
    "Daniel A. Jimenez",
    "Nima Kalantari",
    "John Keyser",
    "Eun Jung (EJ) Kim",
    "Jeeeun Kim",
    "Andreas Klappenecker",
    "Shu Kong",
    "Alan Kuhnle",
    "Sandeep Kumar",
    "Hyunyoung Lee",
    "Teresa Leyk",
    "Robert Lightfoot",
    "Jyh Liu",
    "Dmitri Loguinov",
    "Shawn Lupoli",
    "Rabi N. Mahapatra",
    "J. Michael Moore",
    "Bobak Mortazavi",
    "Robin Murphy",
    "Abdullah Muzahid",
    "Khanh Nguyen",
    "Jason O'Kane",
    "Michael Quinn",
    "Philip Ritchey",
    "Vivek Sarin",
    "Nitesh Saxena",
    "Scott Schaefer",
    "Guni Sharon",
    "Dylan Shell",
    "Frank M. Shipman",
    "Dezhen Song",
    "Radu Stoleru",
    "Shinjiro Sueda",
    "Sing-Hoi Sze",
    "Paul Taele",
    "Shawna Thomas",
    "Chia-Che Tsai",
    "Aakash Tyagi",
    "Nate Veldt",
    "Pauline Wade",
    "Duncan M. 'Hank' Walker",
    "Wenping Wang",
    "Ronald Ward",
    "Tianboa Yang",
    "Ki Hwan Yum",
    "Yupeng Zhang",
]

mathFaculty = [
    'Angela Allen',
    'Patricia Alonso Ruiz',
    'Michael Anshelevich',
    'Amy Austin',
    'Dean Baskin',
    'Guy Battle',
    'Florent Baudier',
    'Gregory Berkolaiko',
    'Harold Boas',
    'Irina Bobkova',
    'Kathryn Bollinger',
    'Andrea Bonito',
    'Justin Cantu',
    'Tamara Carter',
    'Simone Cecchini',
    'Goong Chen',
    'Liwei Chen',
    'Vanessa Coffelt',
    'Andrew Comech',
    'Prabir Daripa',
    'Alan Demlow',
    'Ronald DeVore',
    'Ken Dykema',
    'Yalchin Efendiev',
    'Janice Epstein',
    'Tamas Erdelyi',
    'John Fisk',
    'Ali Foran',
    'Simon Foucart',
    'Bradford Garcia',
    'Nataliia Goncharuk',
    'Sherry Gong',
    'Rostislav Grigorchuk',
    'Jean-Luc Guermond',
    'Alexandru Hening',
    'Yvette Hester',
    'Irina Holmes',
    'Peter Howard',
    'Roger Howe',
    'Bill Johnson',
    'Joe Kahlig',
    'Kendra Kilmer',
    'Joungdong Kim',
    'Patricia Klein',
    'Jeffrey Kuan',
    'Peter Kuchment',
    'Joseph Landsberg',
    'David Larson',
    'Jong Lee',
    'Sang Rae Lee',
    'Paulo Lima-Filho',
    'Chun-Hung Liu',
    'Wencai Liu',
    'Xin Liu',
    'Bret Lockhart',
    'Jonas Luhrmann',
    'Benjamin Lynch',
    'Matthias Maier',
    'David Manuel',
    'Riad Masri',
    'Laura Felicia Matusevich',
    'Francis Narcowich',
    'Volodymyr Nekrashevych',
    'Constantin Onica',
    'Patrick Orchard',
    'Lee Panetta',
    'Grigoris Paouris',
    'Matthew Papanikolas',
    'Gregory Pearlstein',
    'Rosanna Pearlstein',
    'Guergana Petrova',
    'Bojan Popov',
    'Robert Rahm',
    'Kumbakonam Rajagopal',
    'Heather Ramsey',
    'J.N. Reddy',
    'Kamran Reihani',
    'J. Maurice Rojas',
    'Eric Rowell',
    'William Rundell',
    'Vince Schielack',
    'Thomas Schlumprecht',
    'Todd Schrader',
    'Sinjini Sengupta',
    'Oksana Shatalov',
    'Anne Shiu',
    'Jonathan Siegel',
    'John Slattery',
    'Roger Smith',
    'Frank Sottile',
    'Peter Stiller',
    'Emil Straube',
    'Steven Taliaferro',
    'Kyle Thicke',
    'Edriss Titi',
    'Minh-Binh Tran',
    'Marvin Tretkoff',
    'Jessica Tripode',
    'Mariya Vorobets',
    'Yaroslav Vorobets',
    'Kun Wang',
    'John Weeks',
    'Jennifer Whitfield',
    'Michael Willis',
    'Sarah Witherspoon',
    'Stephan Wojtowytsch',
    'Zhizhang Xie',
    'Guangbo Xu',
    'Catherine Yan',
    'Tian Yang',
    'Philip Yasskin',
    'Matthew Young',
    'Guoliang Yu',
    'Igor Zelenko',
    'Jianxin Zhou'
]


physFaculty = [
        'Artem Abanov',
    'Tom Adair',
    'Philip Adsley',
    'Girish Agarwal',
    'Glenn Agnolet',
    'Roland Allen',
    'Meigan Aronson',
    'Bill Bassichis',
    'Katrin Becker',
    'Milivoj Belic',
    'Alexey Belyanin',
    'Carlos Bertulani',
    'Ivan Borzenets',
    'Othmane Bouhali',
    'Siu Chin',
    'Gregory Christian',
    'David Church',
    'Paul Corkum',
    'Luiz Davidovich',
    'Darren DePoy',
    'Bhaskar Dutta',
    'Tatiana Erukhimova',
    'Ricardo Eusebi',
    'Mohammed Farooqi',
    'Alexander Finkelstein',
    'Lewis Ford',
    'Rainer Fries',
    'Ed Fry',
    'Stephen Fulling',
    'Carl Gagliardi',
    'Felipe Guzmán',
    'Joe Ham',
    'John Hardy',
    'Dudley Herschbach',
    'Jeremy Holt',
    'Nathan Holt',
    'Chia-Ren Hu',
    'Wonmuk Hwang',
    'Teruki Kamon',
    'George Kattawar',
    'Ali Kaya',
    'Kevin Kelly',
    'Robert Kennicutt',
    'Vladimir Khmelenko',
    'Che-Ming Ko',
    'Olga Kocharovskaya',
    'Vitaly Kocharovsky',
    'Alexandre Kolomenski',
    'Michael Kordell',
    'Kevin Krisciunas',
    'Wieslaw Krolikowski',
    'David Lee',
    'Igor Lyuksyutov',
    'Lucas Macri',
    'Rupak Mahapatra',
    'Jennifer Marshall',
    'Larry May',
    'Peter McIntyre',
    'Moritz Mehmet',
    'Dan Melconian',
    'Saskia Mioduszewski',
    'Nader Mirabolfathi',
    'Dimitri Nanopoulos',
    'Donald Naugle',
    'Hyunchul Nha',
    'Dawson Nodurft',
    'Casey Papovich',
    'Valery Pokrovsky',
    'Christopher Pope',
    'Xiaofeng Qian',
    'Ralf Rapp',
    'John Reading',
    'Joaquin Rodriguez Nieva',
    'Grigory Rogachev',
    'Joe Ross',
    'Alexei Safonov',
    'John Sarrao',
    'Wayne Saslow',
    'Hans Schuessler',
    'Marlan Scully',
    'Ergin Sezgin',
    'Jairo Sinova',
    'Krista Smith',
    'Alexei Sokolov',
    'Justin Spilker',
    'Louis Strigari',
    'Nicholas Suntzeff',
    'Anatoly Svidzinsky',
    'Winfried Teizer',
    'Dave Toback',
    'Bob Tribble',
    'Stylianos Tzortzakis',
    "William Unruh",
    "Jonelle Walsh",
    "Lifan Wang",
    "Robert Webb",
    "Michael Weimer",
    "George Welch",
    "Wenhao Wu",
    "Shenglong Xu",
    "Vladislav Yakovlev",
    "Ping Yang",
    "Zhenhuan Yi",
    "Dave Youngblood",
    "Michael Youngs",
    "Aleksei Zheltikov",
    "Muhammad Zubairy"
]

ecenFaculty = [
    "Robert S. Balog",
    "Miroslav M. Begovic",
    "Shankar P. Bhattacharyya",
    "Adam Birchfield",
    "Ulisses Braga-Neto",
    "Karen Butler-Purry",
    "Pierce Cantrell, Jr.",
    "Jean-Francois Chamberland",
    "Gwan Choi",
    "Aniruddha Datta",
    "Katherine Davis",
    "Nick Duffield",
    "Mehrdad 'Mark' Ehsani",
    "Prasad Enjeti",
    "Kamran Entesari",
    "Costas N. Georghiades",
    "Paul Gratz",
    "Ibrahim Gunes",
    "Arum Han",
    "Rusty Harris",
    "Philip Hemmer",
    "I-Hong Hou",
    "Sebastian Hoyos",
    "Jiang Hu",
    "Marco Iskander",
    "Roozbeh Jafari",
    "Jim Ji",
    "Stavros Kalafatis",
    "Dileep Kalathil",
    "Aydin Karsilayan",
    "Linda Katehi",
    "Mladen Kezunovic",
    "Sunil Khatri",
    "Soaram Kim",
    "Laszlo B. Kish",
    "Panganamala Kumar ",
    "Pao-Tai Lin",
    "Tie Liu",
    "Mi Lu",
    "John Lusher II",
    "Christi K. Madsen",
    "Krzysztof Arkadiusz Michalski",
    "Scott L. Miller",
    "Oscar Moreira",
    "Krishna Narayanan",
    "Robert D. Nevels",
    "Kevin Nowka",
    "Thomas Overbye",
    "Sam Palermo",
    "Joshua Peeples",
    "Xiaofeng Qian",
    "Xiaoning Qian",
    "Michael Quinn",
    "Mina Rahimian",
    "Jeyavijayan 'JV' Rajendran",
    "Narasimha Reddy",
    "Peter Rentzepis",
    "Raffaella Righetti",
    "B. Don Russell",
    "Serap Savari",
    "Erchin Serpedin",
    "Srinivas Shakkottai",
    'Yang Shen',
    'Weiping Shi',
    'Jose Silva-Martinez',
    'Chanan Singh',
    'Alex Sprintson',
    'Chao Tian',
    'Hamid A. Toliyat',
    'John Tyler',
    'Karan L. Watson',
    'Mark H. Weichold',
    'R. Stanley Williams',
    'Steven M. Wright',
    'Le Xie',
    'Zixiang Xiong',
    'Suin Yi',
    'Byung-Jun Yoon',
    'Xi Zhang',
    'Jun Zou'
]